import Head from "next/head";
import Link from 'next/link';
import styles from "../styles/About.module.css";
import { Gutter } from "../components/layout/Gutter";
import MainNav from "../components/layout/MainNav";
import Footer from "../components/layout/Footer";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Methods :: OEPS Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <script defer data-domain="oeps.healthyregions.org" src="https://plausible.io/js/script.js"></script>
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <MainNav />
      <main className={styles.main}>
        <h1 className={styles.title}>Methodology</h1>

      <Gutter em={5} />

        <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2> Risk Environment Framework</h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
            <p>
                Organization and data selection for the OEPS is guided by a risk environment framework (<a href= "https://www.sciencedirect.com/science/article/pii/S0955395902000075">Rhodes 2002</a>).
                The “risk environment” as a framework for understanding and reducing drug-related harms emphasizes the broader contextual domains
                in which opioid use occurs.
            </p>
            <p>
                Our approach is further rooted in the socioecological model of substance use,
                which includes multiple levels of the physical and social environments that interact and overlap to impact health.
                We apply this socio-ecological model of health and use it to further build on previous research on risk environments
                (Cooper et al 2016, Ciccarone 2017).
            </p>
            <p>
                Data and research models must reflect this transdisciplinary and multi-level approach. The risk environment framework
                shifts the focus of drug-related harm research away from individuals,
                and toward environmental factors driving or enabling trends at the community level.
                We see this approach encouraging greater understanding of the spatial and community contexts in which opioid use harm occurs.
            </p>
          </div>
        </div>

      <Gutter em={2} />

      <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2>Multiple Spatial Scales</h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
            <p>
                Most datasets are available at multiple spatial scales, including Census tract,
                ZIP Code or ZIP Code Tract Area (ZCTA), county, and state. You can filter and explore available datasets by spatial scale <Link href="/docs">here</Link>.
            </p>


          </div>
        </div>

        <Gutter em={2} />

    <div className="row">
        <div className="col-xs-12 col-md-4 col-lg-3">
        <h2>Data Themes</h2>
        </div>
        <div className="col-xs-12 col-md-8 col-lg-9">
        <p>
        Data included in the OEPS is grouped thematically for ease of exploration, indices development, and model integration.
        Data is stratfied across six themes:
        </p>
        <ul>
        <li> <b>Social:</b> Household Characteristics, Demographic measures, Race and Ethnicity, Disability measures, Incarceration rates, Veteran population, Educational Characteristics, Residential Segregation Measures, and Community Overlay Variables </li>
        <li> <b>Economic:</b> Employment Trends, Poverty Measures, and Income Inequality</li>
        <li> <b>Environment:</b> Access to Healthcare Providers, Housing Characteristics, Internet Access, Greenspace Measures, Urbanicity/Rurality, and Alchohol Outlet Density </li>
        <li> <b>Policy:</b> State, county, and local policies that may influence access to treatment and/or criminal justice </li>
        <li> <b>Outcomes:</b> Opioid Indicators and Hepatitis C Rate measures</li>

        </ul>
        <p> <i>Note: Historic Covid-19 data was moved to the <a href="https://www.USCovidAtlas.org">US COVID Atlas</a> --
        a free and open source pandemic data archive and visualization tool, also led by the Healthy Regions and Policies Lab.</i>  </p>

        <p> The OEPS also includes <b>geography boundary</b> shapefiles from the US Census Bureau’s TIGER/Line (Multiple Years) for Census tracts, ZCTAs, counties, and states.</p>

    </div>
  </div>

  <Gutter em={2} />

        <div className="row">
          <div className="col-xs-12 col-md-4 col-lg-3">
            <h2>Census Vintage</h2>
          </div>
          <div className="col-xs-12 col-md-8 col-lg-9">
            <p>
                The Census Bureau updates administrative boundaries for census tracts, counties, and more, on different time scales. Much of the data for 2020 and prior
                uses the 2018 Census Tract vintage, which actually uses the 2010 vintage with slight updates. Access measures were calculated in 2020 and at that time, only
                those 2018 vintages were avialable. Unless otherwise specificed, we use the 2020 Census vintage for 2023 Census measures and later; access measures calculated in 2025 will use the 2020 boundaries, too. 
            </p>
            <p>
                After the 2020 Census was complete, some new boundaries emerged and some existing boundaries changed. Merging newer data to an older boundary
                may thus result in missing values, unless you use the same geographic vintage.
               Be sure to check out the metadata for data you are using to understand which 
                vintage of the data you are using.
            </p>


          </div>
        </div>

        <Gutter em={2} />

    <div className="row">
        <div className="col-xs-12 col-md-4 col-lg-3">
        <h2>Data Standards</h2>
        </div>
        <div className="col-xs-12 col-md-8 col-lg-9">
        <p>
        Please see the <Link href= "/standards">Data Standards</Link> page for more on our file naming conventions, geographic identifiers, data formatting, and guidelines for contributors.
        </p>

    </div>
  </div>

  <Gutter em={2} />

    <div className="row">
        <div className="col-xs-12 col-md-4 col-lg-3">
        <h2>Documentation</h2>
        </div>
        <div className="col-xs-12 col-md-8 col-lg-9">
        <p>
        Please refer to the <Link href= "/docs">Metadata Docs</Link> 
        {/* or the complete <a href= "https://docs.google.com/document/d/18NPWpuUfFTrKll9_ERHzVDmpNCETTzwjJt_FsIvmSrc/edit?usp=sharing">Data Documentation </a> */}
         for more information about individual datasets and variables.
        </p>

    </div>
  </div>


      </main>
      <Footer />
    </div>
  );
}
