from pathlib import Path
import subprocess

import click

from ..clients.bigquery import generate_reference_doc
from ..clients.data_dictionary import create_data_dictionary
from ..handlers import Registry
from ..config import TEMP_DIR
from ..utils import write_csv
from ._common_opts import (
    add_common_opts,
    registry_opt,
)


@click.command()
@click.option(
    "--bq-only",
    is_flag=True,
    default=False,
    help="Only build the BigQuery reference docs.",
)
@click.option(
    "--cli-only",
    is_flag=True,
    default=False,
    help="Only build the CLI docs.",
)
@click.option(
    "--registry-only",
    is_flag=True,
    default=False,
    help="Only build the registry summary docs.",
)
@click.option(
    "--data-dictionaries-only",
    is_flag=True,
    default=False,
    help="Only build the data dictionaries.",
)
@add_common_opts(registry_opt)
def build_docs(bq_only:bool, cli_only: bool, registry_only: bool, data_dictionaries_only:bool, registry_path: Path):
    """Generates various documentation pages based on the data content.

    Optionally only generate one of the types of docs.
    """

    def clean_value(value, md=False):
        if isinstance(value, str):
            return value.replace("\n", "<br>")
        elif isinstance(value, list):
            join_char = "<br/>" if md else ", "
            return join_char.join(value)
        else:
            return str(value)

    ops = {
        "bq": bq_only,
        "cli": cli_only,
        "registry": registry_only,
        "dd": data_dictionaries_only,
    }
    full = not any(ops.values())

    if ops["bq"] or full:
        registry = Registry.create_from_directory(registry_path)

        outfile = Path("../docs/src/reference/bigquery/tables.md").absolute().resolve()
        generate_reference_doc(registry.table_sources.values(), outfile)

    if ops["cli"] or full:
        out_file = Path("../docs/src/reference/cli/command-line-reference.md")

        temp_docs_dir = TEMP_DIR / "cli-docs"
        temp_docs_dir.mkdir(exist_ok=True)
        for p in temp_docs_dir.glob("*.md"):
            p.unlink()

        for p in Path(__file__).parent.glob("*.py"):
            mod = f"oeps.commands.{p.stem}"
            com = p.stem
            mdclick_cmd = [
                "mdclick",
                "dumps",
                "--baseModule",
                mod,
                "--baseCommand",
                com,
                "--docsPath",
                temp_docs_dir,
            ]
            subprocess.run(mdclick_cmd)

        print("Combining individual docs into single file.")
        outlines = []
        for path in temp_docs_dir.glob("*.md"):
            print(path)
            with open(path, "r") as o:
                lines = o.readlines()
                ## per line, downgrade the headers so a single h1 can exist
                for line in lines:
                    for n in reversed(range(1, 7)):
                        old_head, new_head = "#"*n, "#"*(n+1)
                        line = line.replace(old_head, new_head)
                    outlines.append(line)

        with open(out_file, "w") as o:
            o.write("# Command Line Reference")
            o.writelines(outlines)
            o.write(
                "!!! note\n    _This documentatioeen is automatically generated. Do not edit this file directly._\n"
            )

    if ops["registry"] or full:

        registry = Registry.create_from_directory(registry_path)

        ## Create VARIABLES content

        variables = list(registry.variables.values())
        var_cols = [
            "name",
            "title",
            "type",
            "example",
            "description",
            "table_sources",
            "metadata",
            "longitudinal",
            "analysis",
        ]
        var_rows_csv = []
        for var in sorted(variables, key=lambda x: x.name):
            var_rows_csv.append([clean_value(getattr(var, i)) for i in var_cols])

        ## Create THEME content

        metadata_cols = ["theme", "construct", "proxy", "metadata", "url"]
        metadata_rows = []

        for theme, constructs in registry.theme_tree.items():
            for construct, metadata_entries in constructs.items():
                for metadata in metadata_entries:
                    md = registry.metadata[metadata]
                    metadata_rows.append(
                        [theme, construct, md.proxy, metadata, md.url]
                    )

        ## Create TABLE SOURCES content

        table_sources = list(registry.table_sources.values())
        tab_cols = [
            "name",
            "title",
            "path",
            "description",
            "data_year",
            "geodata_source",
        ]
        tab_rows = []
        for tab in table_sources:
            tab_rows.append([clean_value(getattr(tab, i)) for i in tab_cols])

        ## Create GEODATA SOURCES content

        geodata_sources = list(registry.geodata_sources.values())
        geo_cols = [
            "name",
            "summary_level",
            "title",
            "path",
            "description",
        ]
        geo_rows = []
        for gs in geodata_sources:
            geo_rows.append([
                gs.name,
                gs.summary_level.name,
                gs.title,
                gs.path,
                gs.description,
            ])

        dpath = Path("../docs/src/reference/registry/")
        write_csv(dpath / "variables.csv", var_cols, var_rows_csv)
        write_csv(dpath / "metadata.csv", metadata_cols, metadata_rows)
        write_csv(dpath / "table_sources.csv", tab_cols, tab_rows)
        write_csv(dpath / "geodata_sources.csv", geo_cols, geo_rows)

    if ops['dd'] or full:
        print('Creating data dictionaries...')

        registry = Registry.create_from_directory(registry_path)
        outdir = Path("../docs/src/reference/data-dictionaries").absolute().resolve()

        create_data_dictionary(registry, "state", outdir)
        create_data_dictionary(registry, "county", outdir)
        create_data_dictionary(registry, "tract", outdir)
        create_data_dictionary(registry, "zcta", outdir)

        print("  complete.")
