grid-rows: 2
grid-gap: 100

classes {
  config-item: {
    height: 250
  }
}

r: Registry (backend) {
  grid-rows: 1
  grid-columns: 3
}
e: Explorer (frontend) {
  grid-rows: 2
}

r -> e: flask explorer build-config

e.c: Overall configuration {
  grid-columns: 3
}
e.c.v: ""
e.c.v.text: |md
**Variable specifications**

```
config/variables.json
```

- Single file holds all variable definitions
- Lists all tables that have a value for a variable

*This file is created by the `build-config`\
operation and should not be edited directly.*
| {
  class: config-item
}
e.c.s: ""
e.c.s.text: |md
**Source specifications**

```
config/sources/*.json
```

- One JSON file for each geodata source
- Lists all tables (CSVs) that join to it

*These files are created by the `build-config`\
operation and should not be edited directly.*
| {
  class: config-item
}
e.c.sym: "" {
  style: {
    stroke-dash: 2
  }
}
e.c.sym.text: |md
**Variable map display configs**

```
config/symbology.json
```

- Single file holds style definition for each variable
  - color ramp, binning strategies, etc.

*This file is **not** created by the `build-config`\
operation and **should** be edited directly.*
| {
  class: config-item
}

e.p: Raw data {
  grid-columns: 1
}
e.p.csv: ""
e.p.csv.text: |md
  **Public CSV Files**

  ```
  public/csv/*.csv
  ```

  The build process splits all input data source CSVs into subset files based on variable
  presence across multiple sources.

  *These files are created by the `build-config`
  operation and should not be edited directly.*
| {
  height: 120
  width: 1000
}
