title: |md
# OEPS Full Repo Lineage
Lineage of OEPS codebase throughout transition from<br/>
GeoDaCenter to HealthyRegions. Diagram includes two,<br/>
intermediate repos (orange) that were briefly used<br/>
(and may affect observed git history) but are no longer relevant.|
classes {
    gh-repo: {
        style: {
            stroke: black
            fill: white
        }
    }
    directory: {
        style: {
            border-radius: 10
            stroke: purple
        }
    }
    data-repo: {
        style: {
            font-color: green
            stroke: green
            fill: lightgreen
        }
    }
    freeze: {
        shape: stored_data
    }
    branch: {
        shape: parallelogram
    }
    gh-repo-ob {
        style: {
            font-color: orange
            stroke: orange
            stroke-dash: 3
            fill: white
        }
    }
}

geoda: GeoDaCenter/opioid-policy-scan
geoda.class: gh-repo
geoda.main: main branch
geoda.main.class: branch
geoda.explorer: explorer branch
geoda.explorer.class: branch

oeps-be: healthyregions/oeps-backend
oeps-be.class: gh-repo-ob

oeps-be.main: main branch
oeps-be.main.class: branch
oeps-be.main.explorer: /explorer
oeps-be.main.explorer.class: directory
oeps-be.main.backend: /backend
oeps-be.main.backend.class: directory

oeps-ex: healthyregions/oeps-explorer
oeps-ex.class: gh-repo-ob
oeps-ex.main: main branch
oeps-ex.main.class: branch

oeps.explorer: /explorer
oeps.explorer.label: ""
oeps.explorer.class: directory
oeps.explorer.text: |md
## /explorer - Public-facing website
- Data exploration & metadata publishing
- Hosted on Netlify: oeps.healthyregions.org
- References CSVs and Markdown in GeoDaCenter repo |

oeps: healthyregions/oeps
oeps.class: gh-repo
oeps.backend: /backend
oeps.backend.label: ""
oeps.backend.class: directory
oeps.backend.text: |md
## /backend - ETL Scripts
- Import to BigQuery
- Export from BigQUery
- Export from GeoDaCenter repo |

geoda.explorer -> oeps-ex.main: split to new repo\nvia filter {
    style: {
        stroke-dash: 2
    }
}

oeps-ex.main -> oeps-be.main.explorer: merge to new sub-directory {
    style: {
        stroke-dash: 2
    }
}
oeps-ex.main -> oeps-ex.main: |md
rebase entire history,
squash all pre-explorer
data commits | {
    style: {
        stroke-dash: 2
    }
}

oeps-be -> oeps: |md
rename repo;
full history retained |{
    style: {
        stroke-dash: 2
    }
}

geoda.main -> oeps-be.main.backend: |md
data ingested directly
via scripts; no shared history | {
    style: {
        stroke-dash: 2
    }
}
