# render with --pad 25
direction: right
classes: {
    container: {
        style: {
            fill: transparent
            stroke-dash: 3
        }
    }
}
title: |md

  # Connecting variables, sources, and geodata
| {near: top-center}

v: Variables {
    class: container
}
s: Data Sources {
    class: container
}
g: Geodata Sources {
    class: container
}

v.ParkArea: {
    shape: class
    name: ParkArea
    title: Park Area
    data_sources: s-2010
}

v.TotPop: {
    shape: class
    name: TotPop
    title: Total Population
    data_sources: s-2010
    "": s-2000
    " ": c-2010
    "  ": t-2010
}

v.MetTmDr: {
    shape: class
    name: MetTmDr
    title: Drive Time to Methadone Provider
    data_sources: t-2010
}

s.s-2010: {
    shape: class
    name: s-2010
    path: <URL to CSV>

}
s.s-2000: {
    shape: class
    name: s-2000
    path: <URL to CSV>

}
s.c-2010: {
    shape: class
    name: c-2010
    path: <URL to CSV>

}
s.t-2010: {
    shape: class
    name: t-2010
    path: <URL to CSV>
}

g.s: states {
    shape: class
    name: states
    path: <URL to SHP>
}
g.c: counties {
    shape: class
    name: counties
    path: <URL to SHP>
}
g.t: tracts {
    shape: class
    name: tracts
    path: <URL to SHP>
}

s.s-2010 <-> g.s: HEROP_ID
s.s-2000 <-> g.s: HEROP_ID
s.c-2010 <-> g.c: HEROP_ID
s.t-2010 <-> g.t: HEROP_ID

v.ParkArea -> s.s-2010
v.TotPop -> s.s-2010
v.TotPop -> s.s-2000
v.TotPop -> s.c-2010
v.TotPop -> s.t-2010
v.MetTmDr -> s.t-2010
